IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'DbPizzaria')
BEGIN
    CREATE DATABASE DbPizzaria COLLATE Latin1_General_CI_AS;
END
GO

USE DbPizzaria;
GO

CREATE TABLE Usuarios (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Senha NVARCHAR(255) NOT NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    AtualizadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Usuarios PRIMARY KEY (Id),
    CONSTRAINT UQ_Usuarios_Email UNIQUE (Email)
);

CREATE TABLE Categorias (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Nome NVARCHAR(100) NOT NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    AtualizadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Categorias PRIMARY KEY (Id)
);

CREATE TABLE Produtos (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Nome NVARCHAR(100) NOT NULL,
    Preco DECIMAL(18,2) NOT NULL,
    Descricao NVARCHAR(500) NOT NULL,
    Banner NVARCHAR(255) NOT NULL,
    CategoriaId UNIQUEIDENTIFIER NOT NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    AtualizadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Produtos PRIMARY KEY (Id),
    CONSTRAINT FK_Produtos_Categorias FOREIGN KEY (CategoriaId) REFERENCES Categorias(Id) ON DELETE CASCADE
);

CREATE TABLE Pedidos (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Mesa INT NOT NULL,
    Status BIT NOT NULL DEFAULT 0,
    Rascunho BIT NOT NULL DEFAULT 1,
    NomeCliente NVARCHAR(100) NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    AtualizadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Pedidos PRIMARY KEY (Id)
);

CREATE TABLE Itens (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Quantidade INT NOT NULL DEFAULT 1,
    PedidoId UNIQUEIDENTIFIER NOT NULL,
    ProdutoId UNIQUEIDENTIFIER NOT NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    AtualizadoEm DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Itens PRIMARY KEY (Id),
    CONSTRAINT FK_Itens_Pedidos FOREIGN KEY (PedidoId) REFERENCES Pedidos(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Itens_Produtos FOREIGN KEY (ProdutoId) REFERENCES Produtos(Id)
);

CREATE INDEX IX_Produtos_CategoriaId ON Produtos(CategoriaId);
CREATE INDEX IX_Itens_PedidoId ON Itens(PedidoId);
CREATE INDEX IX_Itens_ProdutoId ON Itens(ProdutoId);
CREATE INDEX IX_Pedidos_Status_Rascunho ON Pedidos(Status, Rascunho);